
---
name: pre-merge-ci

on:
  pull_request:
    branches:
    - main

  push:
    branches:
    - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        egress-policy: audit
        disable-telemetry: true

    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install gomplate
      run: make install-gomplate

    - name: Run checks
      env:
        # Installed by previous step
        GOMPLATE: ${HOME}/go/bin/gomplate
      run: make ci
